### ISSUE TITLE
[BUG] When I install torchrl-nightly, it installs 2023.10.25. not nightly

### ISSUE THREAD

**Issue by sakakibara-yuuki** [pytorch/rl#1747]
## Describe the bug

Install torchrl-nightly by `pip install`.
Then, it will be INSTALLED back to the version built on 2023.10.26 from the real nightly.
As a result, the torchrl-nightly of the version built on 2023.10.26 is installed.

## To Reproduce

When,

```bash
pip install torchrl-nightly
```
then, 

```bash
[18:09:38] ~/../hoge   .hoge ❯ pip install torchrl-nightly
Collecting torchrl-nightly
  Downloading torchrl_nightly-2023.12.13-cp39-cp39-manylinux1_x86_64.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 13.8 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.12.12-cp39-cp39-manylinux1_x86_64.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 14.5 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.12.11-cp39-cp39-manylinux1_x86_64.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 15.0 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.12.10-cp39-cp39-manylinux1_x86_64.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 13.6 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.12.9-cp39-cp39-manylinux1_x86_64.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 11.7 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.12.8-cp39-cp39-manylinux1_x86_64.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 13.3 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.12.7-cp39-cp39-manylinux1_x86_64.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 11.9 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.12.6-cp39-cp39-manylinux1_x86_64.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 14.0 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.12.5-cp39-cp39-manylinux1_x86_64.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 14.6 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.12.4-cp39-cp39-manylinux1_x86_64.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 11.3 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.12.3-cp39-cp39-manylinux1_x86_64.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 10.3 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.12.2-cp39-cp39-manylinux1_x86_64.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 14.2 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.12.1-cp39-cp39-manylinux1_x86_64.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 14.0 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.30-cp39-cp39-manylinux1_x86_64.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 10.9 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.29-cp39-cp39-manylinux1_x86_64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 15.5 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.28-cp39-cp39-manylinux1_x86_64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 13.9 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.27-cp39-cp39-manylinux1_x86_64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 13.9 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.26-cp39-cp39-manylinux1_x86_64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 7.7 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.25-cp39-cp39-manylinux1_x86_64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 11.9 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.24-cp39-cp39-manylinux1_x86_64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 14.2 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.23-cp39-cp39-manylinux1_x86_64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 15.6 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.22-cp39-cp39-manylinux1_x86_64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 15.0 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.21-cp39-cp39-manylinux1_x86_64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 11.2 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.20-cp39-cp39-manylinux1_x86_64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 11.7 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.19-cp39-cp39-manylinux1_x86_64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 14.4 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.18-cp39-cp39-manylinux1_x86_64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 11.8 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.17-cp39-cp39-manylinux1_x86_64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 11.5 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.16-cp39-cp39-manylinux1_x86_64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 11.4 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.15-cp39-cp39-manylinux1_x86_64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 7.0 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.14-cp39-cp39-manylinux1_x86_64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 6.7 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.13-cp39-cp39-manylinux1_x86_64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 10.7 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.12-cp39-cp39-manylinux1_x86_64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 11.1 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.11-cp39-cp39-manylinux1_x86_64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 10.8 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.10-cp39-cp39-manylinux1_x86_64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 10.7 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.9-cp39-cp39-manylinux1_x86_64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 10.5 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.6-cp39-cp39-manylinux1_x86_64.whl (5.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 6.3 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.5-cp39-cp39-manylinux1_x86_64.whl (5.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 11.4 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.4-cp39-cp39-manylinux1_x86_64.whl (5.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 14.7 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.3-cp39-cp39-manylinux1_x86_64.whl (5.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 14.1 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.2-cp39-cp39-manylinux1_x86_64.whl (5.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 14.3 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.11.1-cp39-cp39-manylinux1_x86_64.whl (5.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 11.6 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.10.31-cp39-cp39-manylinux1_x86_64.whl (5.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 14.6 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.10.30-cp39-cp39-manylinux1_x86_64.whl (5.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 14.4 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.10.29-cp39-cp39-manylinux1_x86_64.whl (5.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 11.8 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.10.28-cp39-cp39-manylinux1_x86_64.whl (5.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 11.4 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.10.27-cp39-cp39-manylinux1_x86_64.whl (5.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 11.6 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.10.26-cp39-cp39-manylinux1_x86_64.whl (5.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 11.2 MB/s eta 0:00:00
  Downloading torchrl_nightly-2023.10.25-cp39-cp39-manylinux1_x86_64.whl (5.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 14.1 MB/s eta 0:00:00
Collecting cloudpickle
  Downloading cloudpickle-3.0.0-py3-none-any.whl (20 kB)
Collecting torch>=2.1.0.dev
  Downloading torch-2.1.1-cp39-cp39-manylinux1_x86_64.whl (670.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.2/670.2 MB 4.6 MB/s eta 0:00:00
Collecting tensordict-nightly
  Downloading tensordict_nightly-2023.12.13-cp39-cp39-manylinux1_x86_64.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 13.5 MB/s eta 0:00:00
Collecting numpy
  Downloading numpy-1.26.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 14.1 MB/s eta 0:00:00
Collecting packaging
  Downloading packaging-23.2-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 KB 4.6 MB/s eta 0:00:00
Collecting nvidia-nvtx-cu12==12.1.105
  Downloading nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 KB 12.5 MB/s eta 0:00:00
Collecting nvidia-curand-cu12==10.3.2.106
  Downloading nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 15.3 MB/s eta 0:00:00
Collecting filelock
  Downloading filelock-3.13.1-py3-none-any.whl (11 kB)
Collecting jinja2
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 KB 11.1 MB/s eta 0:00:00
Collecting fsspec
  Downloading fsspec-2023.12.2-py3-none-any.whl (168 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 169.0/169.0 KB 17.1 MB/s eta 0:00:00
Collecting nvidia-cudnn-cu12==8.9.2.26
  Downloading nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 4.6 MB/s eta 0:00:00
Collecting nvidia-cusolver-cu12==11.4.5.107
  Downloading nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 12.3 MB/s eta 0:00:00
Collecting triton==2.1.0
  Downloading triton-2.1.0-0-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.3/89.3 MB 11.5 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions in ./.hoge/lib/python3.9/site-packages (from torch>=2.1.0.dev->torchrl-nightly) (4.8.0)
Collecting sympy
  Downloading sympy-1.12-py3-none-any.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 6.9 MB/s eta 0:00:00
Collecting nvidia-cuda-nvrtc-cu12==12.1.105
  Downloading nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 14.5 MB/s eta 0:00:00
Collecting nvidia-cuda-cupti-cu12==12.1.105
  Downloading nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 14.0 MB/s eta 0:00:00
Collecting nvidia-cufft-cu12==11.0.2.54
  Downloading nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 11.0 MB/s eta 0:00:00
Collecting nvidia-cusparse-cu12==12.1.0.106
  Downloading nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 10.6 MB/s eta 0:00:00
Collecting nvidia-nccl-cu12==2.18.1
  Downloading nvidia_nccl_cu12-2.18.1-py3-none-manylinux1_x86_64.whl (209.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.8/209.8 MB 11.5 MB/s eta 0:00:00
Collecting nvidia-cublas-cu12==12.1.3.1
  Downloading nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 6.7 MB/s eta 0:00:00
Collecting nvidia-cuda-runtime-cu12==12.1.105
  Downloading nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 KB 8.5 MB/s eta 0:00:00
Collecting networkx
  Downloading networkx-3.2.1-py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 6.4 MB/s eta 0:00:00
Collecting nvidia-nvjitlink-cu12
  Downloading nvidia_nvjitlink_cu12-12.3.101-py3-none-manylinux1_x86_64.whl (20.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.5/20.5 MB 14.4 MB/s eta 0:00:00
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting mpmath>=0.19
  Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 KB 10.2 MB/s eta 0:00:00
Installing collected packages: mpmath, sympy, packaging, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, numpy, networkx, MarkupSafe, fsspec, filelock, cloudpickle, triton, nvidia-cusparse-cu12, nvidia-cudnn-cu12, jinja2, nvidia-cusolver-cu12, torch, tensordict-nightly, torchrl-nightly
Successfully installed MarkupSafe-2.1.3 cloudpickle-3.0.0 filelock-3.13.1 fsspec-2023.12.2 jinja2-3.1.2 mpmath-1.3.0 networkx-3.2.1 numpy-1.26.2 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.18.1 nvidia-nvjitlink-cu12-12.3.101 nvidia-nvtx-cu12-12.1.105 packaging-23.2 sympy-1.12 tensordict-nightly-2023.12.13 torch-2.1.1 torchrl-nightly-2023.10.25 triton-2.1.0
```

```bash
[12:54:08] ~/../hoge   .hoge ❯ pip list | grep torchrl
torchrl-nightly          2023.10.25
```

## Expected behavior

I was expecting that installing torchrl-nightly would install the latest version, in the example above, version 2023.12.13.

like, 

```bash
[12:54:08] ~/../hoge   .hoge ❯ pip list | grep torchrl
torchrl-nightly          2023.12.13
```

## Screenshots

None

## System info

below is my environment:

 * Ubuntu 22.04.3 LTS (GNU/Linux 5.15.133.1-microsoft-standard-WSL2 x86_64)
 * Python 3.9.13
 * pip 22.0.4

other pip list:

```bash
Package                  Version
------------------------ ------------
annotated-types          0.6.0
anyio                    3.7.1
click                    8.1.7
cloudpickle              3.0.0
exceptiongroup           1.2.0
fastapi                  0.104.1
filelock                 3.13.1
fsspec                   2023.12.2
h11                      0.14.0
idna                     3.6
Jinja2                   3.1.2
MarkupSafe               2.1.3
mpmath                   1.3.0
networkx                 3.2.1
numpy                    1.26.2
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.18.1
nvidia-nvjitlink-cu12    12.3.101
nvidia-nvtx-cu12         12.1.105
packaging                23.2
pip                      22.0.4
pydantic                 2.5.2
pydantic_core            2.14.5
setuptools               58.1.0
sniffio                  1.3.0
starlette                0.27.0
sympy                    1.12
tensordict-nightly       2023.12.13
torch                    2.1.1
torchrl-nightly          2023.10.25
triton                   2.1.0
typing_extensions        4.8.0
uvicorn                  0.24.0.post1
```

## Additional context

When I tried to use DiscreteCQLLoss included in torchrl-nightly, I got an error that MemoryMappedTensor was not found, so I checked the version of torchrl-nightly and noticed that this was happening.

## Reason and Possible fixes
I think the problem is probably related to build-nightly.yaml in github Action, but I don't know the specific solution.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
That seems to be a different issue, let me look into this!

**Comment by vmoens** [comment]
https://github.com/pytorch/tensordict/pull/599 should fix this issue (from tomorrow, when the nightlies will be out)
In the meantime you can always install the library using 
```
$ git clone https://github.com/pytorch/tensordict
$ cd tensordict
$ python setup.py develop
$ cd ..
$ git clone https://github.com/pytorch/rl
$ cd rl
$ python setup.py develop
$ cd ..
```

**Comment by vmoens** [comment]
Thanks for this
I tested it locally and it works. The pytorch package version you're seeing is the nightly release: because we build torchrl-nightly on the pytorch nightly, the package will not work on pytorch stable so we enforce that this version is installed.
To install pytorch nightly, see this page:
https://pytorch.org/get-started/locally/

If you're not willing to change your pytorch version, you will need a local build of torchrl which is fairly easy to get done (see the code  [here](https://github.com/pytorch/rl/issues/1747#issuecomment-1857962978) aboe).
